pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "java-sample-app:1.0"
        CONTAINER_NAME = "java-sample-container"
        APP_PORT = "5000"
        HOST_PORT = "9090"
    }

    stages {
        stage('Cleanup Workspace') {
            steps { deleteDir() }
        }
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build & Test') {
            steps { sh 'mvn clean package' }
        }
        stage('Build Docker Image') {
            steps { sh 'docker build -t ${DOCKER_IMAGE} .' }
        }
        stage('Deploy') {
            steps {
                sh 'docker stop ${CONTAINER_NAME} || true'
                sh 'docker rm ${CONTAINER_NAME} || true'
                sh 'docker run -d --name ${CONTAINER_NAME} -p ${HOST_PORT}:${APP_PORT} ${DOCKER_IMAGE}'
            }
        }
    }

    post {
        success { echo "✅ Pipeline executed successfully!" }
        failure { echo "❌ Pipeline failed. Check logs." }
    }
}



